import type { Metadata } from 'next';
import './globals.css';
import { lora, notoSans } from '@/lib/fonts';
import { cn } from '@/lib/utils';
import { ThemeProvider as NextThemeProvider } from 'next-themes';
import ThemeDataProvider from '@/providers/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import Navbar from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          notoSans.variable,
          lora.variable,
          'antialiased font-noto-sans',
        )}
      >
        <NextThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <ThemeDataProvider>
            <div className='min-h-screen'>{children}</div>
            <Toaster />
          </ThemeDataProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
